### ISSUE TITLE
Running Redis fails

### ISSUE THREAD

**Issue by litashg** [jeremija/peer-calls#92]
Hi Jerko!
I tried to add Redis as store, and I get an error. 

My docker ps
![Screen Shot 2020-04-11 at 9 00 27 AM](https://user-images.githubusercontent.com/31222500/79036747-11caad80-7bd4-11ea-8015-8fcabdef7a63.png)
My config 
![Screen Shot 2020-04-11 at 9 01 03 AM](https://user-images.githubusercontent.com/31222500/79036753-15f6cb00-7bd4-11ea-8161-1d2e91c4e7f2.png)
My error 
![Screen Shot 2020-04-11 at 9 01 36 AM](https://user-images.githubusercontent.com/31222500/79036770-24dd7d80-7bd4-11ea-8e02-940b25797df4.png)

Maybe I make the wrong config?

**Comment by jeremija** [comment]
Are you running a local redis instance?

What happens when you run:

```
redis-cli
```

or

```
redis-cli -h 127.0.0.1 -p 6379
```

**Comment by litashg** [comment]
bash: redis-cli: command not found

**Comment by jeremija** [comment]
Also, you won't be able to use a local redis from a docker instance. You'd have to create a network and link the containers, or use `docker-compose` for this:

```
version: '3.1'

services:
  redis:
    image: redis:5-alpine
    restart: always
  peercalls:
    image: peer-calls:latest
    restart: always
    links:
      - redis
    ports:
      - 3000:3000
```

Now you should be able to use `host: redis` and `port: 6379`.

**Comment by litashg** [comment]
Added new docker-compose.yml, changed the config to : 
```
version: '3.1'

services:
  redis:
    image: redis:5-alpine
    restart: always
  peercalls:
    image: peer-calls:latest
    restart: always
    links:
    - redis
    ports:
    - 3000:3000
```
Rebuilded all an up. 
![Screen Shot 2020-04-11 at 9 25 55 AM](https://user-images.githubusercontent.com/31222500/79037055-a8986980-7bd6-11ea-8d33-ecca4749b897.png)

**Comment by jeremija** [comment]
> Now you should be able to use host: redis and port: 6379.

Change the redis host to `redis`

**Comment by litashg** [comment]
Like this ? 
![Screen Shot 2020-04-11 at 9 33 07 AM](https://user-images.githubusercontent.com/31222500/79037190-8521ee80-7bd7-11ea-81da-1be77b0c91ec.png)

**Comment by jeremija** [comment]
yes, it has to be the same as the name of the container in a `docker-compose` file.

**Comment by litashg** [comment]
Nothing changes :(

**Comment by jeremija** [comment]
What happens if you run only this, without any config files?

```yaml
version: '3.1'

services:
  redis:
    image: redis:5-alpine
    restart: always
  peercalls:
    image: jeremija/peer-calls:latest
    restart: always
    environment:
      PEERCALLS__STORE: '{"type":"redis","host":"redis","port":"6379"}'
    links:
    - redis
    ports:
    - 3000:3000
```

**Comment by litashg** [comment]
It works for me too. But is it ok to put store config into docker-compose.yml?

**Comment by jeremija** [comment]
It depends. You might want to use a separate file like [`.env`](https://docs.docker.com/compose/environment-variables/#the-env-file).

If you want to use a local config file using `docker-compose`, the easiest way is to write the file to `./config/local.yaml`, and then add the `config/` directory as a volume:

```
services:
  peercalls:
    volumes:
      - './config:./config'
```
